server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
  forward-headers-strategy: framework

spring:
  application:
    name: impresser
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    compress:
      exchange: ${COMPRESS_EXCHANGE}
    print:
      exchange: ${PRINT_EXCHANGE}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    com.semes.impresser: INFO

s3:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
  region: us-east-1

external:
  api:
    base-url: ${EXTERNAL_CONVERT_BASE_URL}
    connect-timeout-ms: ${EXTERNAL_CONVERT_CONNECT_TIMEOUT:3000}
    read-timeout-ms: ${EXTERNAL_CONVERT_READ_TIMEOUT:5000}
