include /etc/nginx/conf.d/upstream.backend.dev.conf;
include /etc/nginx/conf.d/upstream.backend.prod.conf;

server {
  listen 443 ssl;
  http2 on;
  server_name k13s404.p.ssafy.io;

  ssl_certificate     /etc/nginx/ssl/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/privkey.pem;

  resolver 127.0.0.11 valid=5s;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location / {
    proxy_pass http://frontend-prod:3000;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
  }
  location /api/ {
    proxy_pass http://backend_upstream_prod;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
  }

    location /rabbitmq-prod/ {
    proxy_pass http://rabbitmq-prod:15672/; 
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }

  location /rabbitmq-dev/ {
    proxy_pass http://rabbitmq-dev:15672/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }

  location /jenkins/ {
    proxy_pass http://jenkins:8080/jenkins/;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 300s;
  }
}

server {
  listen 8443 ssl;
  http2 on;
  server_name k13s404.p.ssafy.io;

  ssl_certificate     /etc/nginx/ssl/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/privkey.pem;

  resolver 127.0.0.11 valid=5s;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location / {
    proxy_pass http://frontend-dev:3000;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
  }
  location /api/ {
    proxy_pass http://backend_upstream_dev;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
  }
}

server {
  listen 80;
  server_name k13s404.p.ssafy.io;
  return 301 https://$host$request_uri;
}